#spring:
#  application:
#    name: uniTrade
#  web:
#    resources:
#      static-locations: classpath:/static/
#  data:
#    mongodb:
#      uri: ${SPRING_DATA_MONGODB_URI}
#      database: ${SPRING_DATA_MONGODB_DATABASE}
#
